### ISSUE TITLE
pip install misaka==2.0.0 error and pip install misaka==1.0.2 successfully with debian 8 64-bit

### ISSUE THREAD

**Issue by ego008** [FSX/misaka#51]
```
/misaka-1.0.2$ sudo python setup.py install
running install
running bdist_egg

...

Installed /usr/local/lib/python2.7/dist-packages/misaka-1.0.2-py2.7-linux-x86_64.egg
Processing dependencies for misaka==1.0.2
Finished processing dependencies for misaka==1.0.2
```

```
$ sudo pip install --upgrade  misaka
Downloading/unpacking misaka from https://pypi.python.org/packages/source/m/misaka/misaka-2.0.0.tar.gz#md5=79352edb71f604402277d8bb6d3a54ef
  Downloading misaka-2.0.0.tar.gz (121kB): 121kB downloaded
  Running setup.py (path:/tmp/pip-build-yNLUKN/misaka/setup.py) egg_info for package misaka
    
    Installed /tmp/pip-build-yNLUKN/misaka/.eggs/cffi-1.3.0-py2.7-linux-x86_64.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-yNLUKN/misaka/setup.py", line 68, in <module>
        cffi_modules=['build_ffi.py:ffi'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 272, in __init__
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 327, in finalize_options
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2370, in load
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2376, in resolve
    ImportError: No module named setuptools_ext
    Complete output from command python setup.py egg_info:
    

Installed /tmp/pip-build-yNLUKN/misaka/.eggs/cffi-1.3.0-py2.7-linux-x86_64.egg
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip-build-yNLUKN/misaka/setup.py", line 68, in <module>
    cffi_modules=['build_ffi.py:ffi'],
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 272, in __init__
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 327, in finalize_options
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2370, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2376, in resolve
ImportError: No module named setuptools_ext

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-yNLUKN/misaka
Storing debug log for failure in /root/.pip/pip.log

```

`setuptools`  was installed:

```
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> 

```

**Comment by FSX** [comment]
What happens if you run `pip install --upgrade cffi` and try t install Misaka again?

**Comment by ego008** [comment]
Thank you @FSX 
Installing libffi-dev and cffi  fixed this issue for me.
