### ISSUE TITLE
Error in Installing misaka

### ISSUE THREAD

**Issue by Sahil624** [FSX/misaka#64]
`Collecting misaka==2.1.0
  Using cached misaka-2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 169, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 155, in call_command
        self.run_command(cmdname)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
        yield saved
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
        _execfile(setup_script, ns)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-kvh6gbri/cffi-1.10.0/setup.py", line 232, in <module>
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
        run_setup(setup_script, args)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 257, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 170, in save_modules
        saved_exc.resume()
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 145, in resume
        six.reraise(type, exc, self._tb)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
        yield saved
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
        _execfile(setup_script, ns)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-kvh6gbri/cffi-1.10.0/setup.py", line 232, in <module>
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l03_gsni/misaka/setup.py", line 76, in <module>
        cffi_modules=['build_ffi.py:ffi'],
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/sahil/Documents/news-for-good/my_app/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l03_gsni/misaka/
`

This was The error I got When I used command 
`pip install misaka==2.1.0`
I even Tried pip3.

I have installed build-essential, python-dev and libffi-dev as said in documentation.

But still, I am getting the error.
Can anyone help, please?

**Comment by Sahil624** [comment]
I pip installed cffi , now I am at  [https://github.com/numba/llvmlite/issues/166](this Issue).
I guess That can be a little promotion.
