### ISSUE TITLE
Error pip install misaka in Windows 8.1 64 bit

### ISSUE THREAD

**Issue by AlexVillegas** [FSX/misaka#65]
Helllo.
I have Windows 8.1 64bit, I need install misaka in Python 3.6.1|Anaconda 4.4.0 64 bit, but when I trying install say : 
(DjangoEnv) c:\Python36\envs>pip install misaka==2.1.0
Collecting misaka==2.1.0
  Using cached misaka-2.1.0.tar.gz
Requirement already satisfied: cffi>=1.0.0 in c:\python36\envs\djangoenv\lib\sit
e-packages (from misaka==2.1.0)
Requirement already satisfied: pycparser in c:\python36\envs\djangoenv\lib\site-
packages (from cffi>=1.0.0->misaka==2.1.0)
Building wheels for collected packages: misaka
  Running setup.py bdist_wheel for misaka ... error
  **Failed building wheel for misaka**
  Running setup.py clean for misaka
**Failed to build misaka**
Installing collected packages: misaka
  Running setup.py install for misaka ... error
Exception:
Traceback (most recent call last):
  **File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\compat\__init__.py", li
ne 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 102: invali
d continuation byte**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\commands\install.py", l
ine 342, in run
    prefix=options.prefix_path,
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\req\req_set.py", line 7
84, in install
    **kwargs
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\req\req_install.py", li
ne 878, in install
    spinner=spinner,
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\utils\__init__.py", lin
e 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\compat\__init__.py", li
ne 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 102: invali
d continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\commands\install.py", l
ine 385, in run
    requirement_set.cleanup_files()
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\req\req_set.py", line 7
29, in cleanup_files
    req.remove_temporary_source()
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\req\req_install.py", li
ne 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\retrying.py", l
ine 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\retrying.py", l
ine 212, in call
    raise attempt.get()
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\retrying.py", l
ine 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\six.py", line 6
86, in reraise
    raise value
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\retrying.py", l
ine 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\utils\__init__.py", lin
e 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Python36\envs\DjangoEnv\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python36\envs\DjangoEnv\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\utils\__init__.py", lin
e 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está
 siendo utilizado por otro proceso: 'C:\\Users\\ALEXVI~1\\AppData\\Local\\Temp\\
pip-build-h94adwhp\\misaka'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\basecommand.py", line 2
15, in main
    status = self.run(options, args)
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\commands\install.py", l
ine 385, in run
    requirement_set.cleanup_files()
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\utils\build.py", line 3
8, in __exit__
    self.cleanup()
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\utils\build.py", line 4
2, in cleanup
    rmtree(self.name)
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\retrying.py", l
ine 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\retrying.py", l
ine 212, in call
    raise attempt.get()
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\retrying.py", l
ine 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\six.py", line 6
86, in reraise
    raise value
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\_vendor\retrying.py", l
ine 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\utils\__init__.py", lin
e 102, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Python36\envs\DjangoEnv\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python36\envs\DjangoEnv\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python36\envs\DjangoEnv\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python36\envs\DjangoEnv\lib\site-packages\pip\utils\__init__.py", lin
e 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está
 siendo utilizado por otro proceso: 'C:\\Users\\ALEXVI~1\\AppData\\Local\\Temp\\
pip-build-h94adwhp\\misaka'

**Comment by chahalx** [comment]
please help me in the same matter??? any solutions?

**Comment by FSX** [comment]
Maybe this helps: https://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/

I have have Windows and enough time to figure it out.
