### ISSUE TITLE
Error with SaferHtmlRenderer

### ISSUE THREAD

**Issue by samuelcolvin** [FSX/misaka#66]
Problem is at 

https://github.com/FSX/misaka/blob/dcf87c8a062d0416d702541e544cd4285a1459c0/misaka/api.py#L345

Should be relatively simple to fix with 

```py
return ('<a href="%s"%s>'  % (url, maybe_title))  + content + '</a>'
```

Or similar

Example of the error:

```
In [1]: from misaka import Markdown, SaferHtmlRenderer

In [2]: safer_markdown = Markdown(SaferHtmlRenderer())

In [3]: s='[![xxx](http://www.example.com/?v=%s)](http://www.example.com/])'

In [4]: safer_markdown(s)
From cffi callback <function cb_link at 0x7f7a0cd83598>:
Traceback (most recent call last):
  File "/home/samuel/code/nosht/env/lib/python3.6/site-packages/misaka/callbacks.py", line 301, in cb_link
    result = renderer.link(content, link, title)
  File "/home/samuel/code/nosht/env/lib/python3.6/site-packages/misaka/api.py", line 345, in link
    return ('<a href="%s"%s>' + content + '</a>') % (url, maybe_title)
TypeError: not enough arguments for format string
Out[4]: '<p>[<img src="http://www.example.com/?v=%s" alt="xxx" />](http://www.example.com/])</p>\n'
```

**Comment by FSX** [comment]
Thanks for the report @samuelcolvin!

Sorry for the slow response. Was caught up in work. :(

I pushed a fix: https://github.com/FSX/misaka/commit/587edde849a9188300e87d3d3773a9531a2634a7. Can you verify it works on your side? I can make a release shortly.

**Comment by samuelcolvin** [comment]
I'm away from my computer this week.

Looks good to me although I think you have a double space (not sure if you care).

**Comment by FSX** [comment]
Fixed.

**Comment by samuelcolvin** [comment]
Thank you so much.
